# Generated by Django 5.1.7 on 2025-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.FloatField(blank=True, help_text='Estimated duration in hours', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, help_text='Comma-separated tags', null=True),
        ),
    ]
